language: node_js

addons:
  chrome: stable

node_js:
  - "stable"

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn test
  - yarn build

deploy:
  - provider: s3
    region: "us-east-1"
    bucket: "allthetags.com"
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    local_dir: build
    default_text_charset: "utf-8"
    skip_cleanup: true
    on: 
      branch: "master"
  - provider: s3
    region: "us-east-1"
    bucket: "develop.allthetags.com"
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    default_text_charset: "utf-8"
    local_dir: build
    skip_cleanup: true
    on: 
      branch: "develop"
