language: node_js

sudo: required

addons:
  chrome: stable

node_js:
  - "stable"

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn test
  - yarn build
  - yarn build-snap

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  local_dir: build
  default_text_charset: "utf-8"
  bucket: "joshduck.com"
  region: "ap-southeast-2"
  local_dir: build